### ISSUE TITLE
Eos not defined, missing eos.js

### ISSUE THREAD

**Issue by c052463** [tokenika/secure-bp-voting#16]
Disclaimer: I am not a dev.

I tried generating a transaction offline, failed.
In browser console.
Received a warning:
- Use of getPreventDefault() is deprecated. Use defaultPrevented instead. 

Received an error:
- Eos is not defined.

How I got it working:
1. I downloaded eos.js from official EOS github folder, pasted it in same folder as 2_generate_transaction.html
2. Replaced
`<script src="https://github.com/EOSIO/eosjs/releases/download/v14.1.1/eos.js"></script>`
with
`<script src="eos.js"></script>`
in
[2_generate_transaction.html](https://github.com/tokenika/secure-bp-voting/blob/7509839c2c83eeecc0b51fa80c76abefa811900d/2_generate_transaction.html#L4)

Was it suppose to work without doing what I did?

**Comment by noisy** [comment]
Please follow the instructions provided on https://tokenika.github.io/secure-bp-voting/2_generate_transaction.html :)

> First of all, save this website to your local machine (right click, Save as…)

Goal of Tokenika is to **not add** build version of `eos.js` library directly to this repository, because it would be very difficult for everyone to audit this file, and make sure, that we didn't altered it.

That's why we are linking to official repository and to file build by Block One, not by us.

If a user follows the instructions provided by us, then a browser downloads linked file automatically, when a user click "Save as...". If someone prefer to clone a repository, then he needs to download eos.js file on his own. But we recommend first method because of simplicity.

**Comment by c052463** [comment]
Thank you for highlighting that. My apologizes for assuming downloading the whole zip would work.
I just downloaded the zip and that is why the error occurred.

You are doing great job!!
